### PR TITLE
Fix linking error on FreeBSD

### PR DESCRIPTION
**Pull request by neelchauhan**
I fixed the error when linking Astron on FreeBSD. FreeBSD does need -pthread but not -lrt.

### CODE REVIEW

**Comment by bobbybee** [comment]
Not on FreeBSD here, but looks good :+1:

**Comment by xHarv14** [comment]
Before I :+1: this, did you actually try following the error message in #358 and adding ```-lthr```?

**Comment by AlJaMa** [comment]
👍

**Comment by neelchauhan** [comment]
I did not use -lthr. Just -pthread worked fine for me.

**Comment by neelchauhan** [comment]
When I try to run astrond on FreeBSD, I get "Segmentation fault". Here is the full output (including the gdb output):

>[100%] Linking CXX executable astrond
>[100%] Built target astrond
>neel@megan:~/tmp/Astron % ./astrond 
>Segmentation fault (core dumped)
>neel@megan:~/tmp/Astron % gdb astrond
>GNU gdb 6.1.1 [FreeBSD]
>Copyright 2004 Free Software Foundation, Inc.
>GDB is free software, covered by the GNU General Public License, and you are
>welcome to change it and/or distribute copies of it under certain conditions.
>Type "show copying" to see the conditions.
>There is absolutely no warranty for GDB.  Type "show warranty" for details.
>This GDB was configured as "amd64-marcel-freebsd"...
>(gdb) run
>Starting program: /usr/home/neel/tmp/Astron/astrond 
>[New LWP 100234]
>[New Thread 802c06400 (LWP 100234/astrond)]
>
>Program received signal SIGSEGV, Segmentation fault.
>[Switching to Thread 802c06400 (LWP 100234/astrond)]
>0x0000000801c774ca in pthread_mutex_lock () from /lib/libthr.so.3
>(gdb)

**Comment by boynedmaster** [comment]
:+1:

**Comment by mfwass** [comment]
@neelchauhan You'd need to type "bt" into gdb. That'll give them a stack trace of the crash (make sure you have Astron built in debug when you do that!)

**Comment by neelchauhan** [comment]
This is my backtrace

#0  0x0000000801c9967a in pthread_mutex_lock () from /lib/libthr.so.3
#1  0x00000000004100b5 in boost::asio::detail::posix_mutex::lock (this=0x8)
    at posix_mutex.hpp:52
#2  0x000000000040fe23 in scoped_lock (this=0x7fffffffd6a0, m=@0x8)
    at scoped_lock.hpp:46
#3  0x000000000049b7e5 in boost::asio::detail::service_registry::do_use_service
    (this=0x0, key=@0x7fffffffd6f8, 
    factory=0x49b750 <boost::asio::io_service::service* boost::asio::detail::service_registry::create<boost::asio::datagram_socket_service<boost::asio::ip::udp> >(boost::asio::io_service&)>) at service_registry.ipp:108
#4  0x000000000049b70e in boost::asio::detail::service_registry::use_service<boost::asio::datagram_socket_service<boost::asio::ip::udp> > (this=0x0)
    at service_registry.hpp:48
#5  0x000000000049b658 in boost::asio::use_service<boost::asio::datagram_socket_service<boost::asio::ip::udp> > (ios=@0x883770) at io_service.hpp:33
#6  0x0000000000499fd9 in basic_io_object (this=0x8844c8, io_service=@0x883770)
    at basic_io_object.hpp:183
#7  0x0000000000499f08 in basic_socket (this=0x8844c8, io_service=@0x883770, 
    protocol=@0x7fffffffd860) at basic_socket.hpp:89
#8  0x0000000000493320 in basic_datagram_socket (this=0x8844c8, 
    io_service=@0x883770, protocol=@0x7fffffffd860)
    at basic_datagram_socket.hpp:89
#9  0x00000000004904d2 in EventSender (this=0x884498)
    at /home/neel/tmp/Astron/src/util/EventSender.cpp:8
#10 0x0000000000490ad7 in __cxx_global_var_init25 ()
    at /home/neel/tmp/Astron/src/util/EventSender.cpp:46
#11 0x00000000004932e9 in global constructors keyed to a ()
    at /home/neel/tmp/Astron/src/util/EventSender.cpp:358
#12 0x000000000060fc22 in __do_global_ctors_aux ()
#13 0x000000000040b4d6 in _init ()
#14 0x00007fffffffdd50 in ?? ()
#15 0x0000000800885a9f in r_debug_state () from /libexec/ld-elf.so.1
#16 0x00000008008850ee in __tls_get_addr () from /libexec/ld-elf.so.1
#17 0x0000000800883439 in .text () from /libexec/ld-elf.so.1
#18 0x0000000000000000 in ?? ()

**Comment by AlJaMa** [comment]
What's the status of this PR?

**Comment by neelchauhan** [comment]
Unfortunately, no progress is being made. I haven't done any further work on this.

**Comment by neelchauhan** [comment]
I have some news: Astron now runs on FreeBSD.

	neel@megora:~/tmp/Astron % ./astrond 
	[2016-11-24 07:30:30] INFO: Main: Loading configuration file...
	[2016-11-24 07:30:30] FATAL: Main: Failed to open configuration file "astrond.yml".
	neel@megora:~/tmp/Astron % 

I did not have any configuration file to work on, but at least it doesn't segfault anymore!

I don't know if it was on Astron's side or Boost's, but FreeBSD Ports (FreeBSD's apt-get/yum/pacman) just got an updated Boost, along with updates to Astron's main code.

**Comment by bobbybee** [comment]
# Woo-hoo!

I think

**Comment by AlJaMa** [comment]
So is this PR required any more?

**Comment by xHarv14** [comment]
Closing as resolved

**Pull request closed without merging**
