### PR TITLE
Add boost as a  dependency

### PR DESCRIPTION
**Pull request by mgracer48**

### CODE REVIEW

**Comment by mgracer48** [comment]
Tell me why closed?

**Comment by CFSworks** [comment]
I can't speak for @AlJaMa but PRs should be going into the "develop" branch now, rather than "master" -- I don't know if that's the only reason, though.

**Comment by mgracer48** [comment]
Thanks shockley

**Comment by AlJaMa** [comment]
What @CFSworks said, as well as you had multiple PR's for the same file. If you are going to do a PR please do something like "updating dependencies" and have multiple commits within that. 

Also, a better place for dependencies would be on the github.io documentation page.

@mgracer48... not sure who you are referring to there.

**Comment by mgracer48** [comment]
@AlJaMa cfsworks is refered to as shockley in toontown rewritten

**Comment by AlJaMa** [comment]
@mgracer48, good to know. A reminder, this project is not affiliated with toon town rewritten.

**Comment by mgracer48** [comment]
i know that :)

**Pull request closed without merging**
