### PR TITLE
MongoDB backend!

### PR DESCRIPTION
**Pull request by CFSworks**
This is pretty much done! Just needs a sign-off and it can be merged down.

### CODE REVIEW

**Comment by xHarv14** [comment]
Based on the success we've had with running this in a production environment (Debian)... :+1: I've also had success with running this in a Windows environment for development.

I haven't ran any unit tests, so someone should run those before merging this down.

**Comment by AlJaMa** [comment]
Currently failing to build on OS X. With the following build log. It's strange that it's in the dclass target.
```
Alexs-MacBook-Pro:build alex$ make
[ 35%] Built target dclass
[ 37%] Building CXX object CMakeFiles/astrond.dir/src/config/ConfigGroup.cpp.o
In file included from /Users/alex/Desktop/astron/src/config/ConfigGroup.cpp:1:
In file included from /Users/alex/Desktop/astron/src/config/ConfigGroup.h:6:
In file included from /usr/local/include/yaml-cpp/yaml.h:20:
/usr/local/include/yaml-cpp/node/detail/impl.h:136:9: error: use of undeclared identifier 'equals'
    if (equals(*it->first, key, pMemory)) {
        ^
/usr/local/include/yaml-cpp/node/detail/node_ref.h:69:21: note: in instantiation of function template specialization
      'YAML::detail::node_data::remove<std::__1::basic_string<char> >' requested here
    return m_pData->remove(key, pMemory);
                    ^
/usr/local/include/yaml-cpp/node/detail/node.h:131:20: note: in instantiation of function template specialization
      'YAML::detail::node_ref::remove<std::__1::basic_string<char> >' requested here
    return m_pRef->remove(key, pMemory);
                   ^
/usr/local/include/yaml-cpp/node/impl.h:392:19: note: in instantiation of function template specialization
      'YAML::detail::node::remove<std::__1::basic_string<char> >' requested here
  return m_pNode->remove(detail::to_value(key), m_pMemory);
                  ^
/Users/alex/Desktop/astron/src/config/ConfigGroup.cpp:139:16: note: in instantiation of function template
      specialization 'YAML::Node::remove<std::__1::basic_string<char> >' requested here
    child_node.remove(m_key);
               ^
1 error generated.
make[2]: *** [CMakeFiles/astrond.dir/src/config/ConfigGroup.cpp.o] Error 1
make[1]: *** [CMakeFiles/astrond.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by xHarv14** [comment]
@AlJaMa Did you make any additional changes? I was able to compile on OS X successfully.

**Comment by mfwass** [comment]
I'm failing on OS X too. Here's the build log:

```
[ 84%] Building CXX object CMakeFiles/astrond.dir/src/tests/MDParticipantTest.cpp.o
/Users/Michael/Documents/Astron/src/tests/MDParticipantTest.cpp:27:18: warning: 
      'MDParticipantTest::handle_datagram' hides overloaded virtual function
      [-Woverloaded-virtual]
    virtual void handle_datagram(Datagram &dg, DatagramIterator &dgi)
                 ^
/Users/Michael/Documents/Astron/src/messagedirector/MessageDirector.h:114:18: note: 
      hidden overloaded virtual function
      'MDParticipantInterface::handle_datagram' declared here: type mismatch at
      1st parameter ('DatagramHandle' (aka 'shared_ptr<const Datagram>') vs
      'Datagram &')
    virtual void handle_datagram(DatagramHandle dg, DatagramIterator &dgi) = 0;
                 ^
/Users/Michael/Documents/Astron/src/tests/MDParticipantTest.cpp:12:18: error: 
      calling a protected constructor of class 'Datagram'
        Datagram dg2;
                 ^
/Users/Michael/Documents/Astron/src/util/Datagram.h:63:5: note: declared
      protected here
    Datagram() : buf(new uint8_t[64]), buf_cap(64), buf_offset(0)
    ^
/Users/Michael/Documents/Astron/src/tests/MDParticipantTest.cpp:18:36: error: 
      no member named 'handle_datagram' in 'MessageDirector'; did you mean
      'route_datagram'?
        MessageDirector::singleton.handle_datagram(NULL, dg2);
                                   ^~~~~~~~~~~~~~~
                                   route_datagram
/Users/Michael/Documents/Astron/src/messagedirector/MessageDirector.h:37:10: note: 
      'route_datagram' declared here
    void route_datagram(MDParticipantInterface *p, DatagramHandle dg);
         ^
/Users/Michael/Documents/Astron/src/tests/MDParticipantTest.cpp:18:58: error: 
      no viable conversion from 'Datagram' to 'DatagramHandle' (aka
      'shared_ptr<const Datagram>')
        MessageDirector::singleton.handle_datagram(NULL, dg2);
                                                         ^~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3761:23: note: 
      candidate constructor not viable: no known conversion from 'Datagram' to
      'nullptr_t' for 1st argument
    _LIBCPP_CONSTEXPR shared_ptr(nullptr_t) _NOEXCEPT;
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3786:5: note: 
      candidate constructor not viable: no known conversion from 'Datagram' to
      'const std::__1::shared_ptr<const Datagram> &' for 1st argument
    shared_ptr(const shared_ptr& __r) _NOEXCEPT;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3792:5: note: 
      candidate constructor not viable: no known conversion from 'Datagram' to
      'std::__1::shared_ptr<const Datagram> &&' for 1st argument
    shared_ptr(shared_ptr&& __r) _NOEXCEPT;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3788:9: note: 
      candidate template ignored: could not match
      'shared_ptr<type-parameter-0-0>' against 'Datagram'
        shared_ptr(const shared_ptr<_Yp>& __r,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3793:25: note: 
      candidate template ignored: could not match
      'shared_ptr<type-parameter-0-0>' against 'Datagram'
    template<class _Yp> shared_ptr(shared_ptr<_Yp>&& __r,
                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3806:9: note: 
      candidate template ignored: could not match 'auto_ptr<type-parameter-0-0>'
      against 'Datagram'
        shared_ptr(auto_ptr<_Yp>&& __r);
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3824:8: note: 
      candidate template ignored: could not match
      'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'Datagram'
       shared_ptr(unique_ptr<_Yp, _Dp>&&,
       ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3833:8: note: 
      candidate template ignored: could not match
      'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'Datagram'
       shared_ptr(unique_ptr<_Yp, _Dp>&&,
       ^
/Users/Michael/Documents/Astron/src/messagedirector/MessageDirector.h:37:67: note: 
      passing argument to parameter 'dg' here
    void route_datagram(MDParticipantInterface *p, DatagramHandle dg);
                                                                  ^
/Users/Michael/Documents/Astron/src/tests/MDParticipantTest.cpp:27:44: warning: 
      unused parameter 'dg' [-Wunused-parameter]
    virtual void handle_datagram(Datagram &dg, DatagramIterator &dgi)
                                           ^
/Users/Michael/Documents/Astron/src/tests/MDParticipantTest.cpp:33:19: error: 
      variable type 'MDParticipantTest' is an abstract class
MDParticipantTest unittest_mdparticipant;
                  ^
/Users/Michael/Documents/Astron/src/messagedirector/MessageDirector.h:114:18: note: 
      unimplemented pure virtual method 'handle_datagram' in 'MDParticipantTest'
    virtual void handle_datagram(DatagramHandle dg, DatagramIterator &dgi) = 0;
                 ^
2 warnings and 4 errors generated.
make[2]: *** [CMakeFiles/astrond.dir/src/tests/MDParticipantTest.cpp.o] Error 1
make[1]: *** [CMakeFiles/astrond.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mfwass** [comment]
EDIT:

If tests is excluded in CMake then everything builds fine.

**Comment by alexbegt** [comment]
I keep failing on ubuntu with trying to compile the MongoDatabase.cpp because of boost and std

**Comment by AlJaMa** [comment]
+1 Finally got working on OS X. Merging :)

**Comment by bobbybee** [comment]
Awesome.

**Comment by mfwass** [comment]
:+1:

**Pull request merged**
