### PR TITLE
README formatting; correct grammatical errors.

### PR DESCRIPTION
**Pull request by mfwass**

### CODE REVIEW

**Comment by bobbybee** [comment]
The tables feel 'noisy' to me. Thoughts?

**Comment by AlJaMa** [comment]
I appreciate the contents… But is it all needed in the README?  Also there are several grammatical errors

**Comment by mfwass** [comment]
@bobbybee It keeps it pretty organized, to me at least.
@AlJaMa Whenever I notice a grammatical error I just send off a quick PR. Even though the README isn't being graded as an English paper, it's still nice to have some of the grammatical errors fixed.

**Comment by mfwass** [comment]
@AlJaMa @bobbybee  Any updates on this PR's status?

**Comment by AlJaMa** [comment]
As I said before, multiple errors exist in this PR. 
Additionally, the diff is very noisy. Please submit a PR that is more targeted then re-writing the entire thing.

**Pull request closed without merging**
