### PR TITLE
Resolve race condition with interests

### PR DESCRIPTION
**Pull request by CFSworks**
This pull request resolves a long-standing issue with interests in the client agent, where a race between an object entering a zone and the CA opening the interest would result in the CA miscounting the objects.

This issue is twofold, since the race may cause the CA to either:
1. Stall indefinitely, if an object left after the count was calculated.
2. Prematurely tell the client that the interest is open, if an object snuck in after the count was calculated.

I have resolved the indefinite stalling by adding a timeout to InterestOperation.
Some changes were necessary for this:
* I had to make InterestOperation referenced by pointer, rather than copied. This way its `this` pointer would not change.
* InterestOperations track the client, and have a little bit more autonomy than the basic "struct with methods" they (essentially) were before.
* I added a "timeout" class to util/, which allows specification of an arbitrary timeout and callback.
* I put the configuration variable `interest_timeout` in the Client (i.e. *base*) class, since this behavior is not specific to AstronClient.

I resolved the premature issue by giving the parent and child objects slightly better communication about who knows what. I added a new message called `STATESERVER_OBJECT_LOCATION_ACK`, which is sent to a child when it gets factored into the zone counts. When the child announces itself to an interested peer, it uses ENTER_INTEREST if it has received a LOCATION_ACK (i.e. the parent knows it exists and included it in the count) and ENTER_LOCATION otherwise.

Furthermore, I went ahead and removed the "self-decrementing" behavior on InterestOperations -- it's too prone to error and the timeout will catch those cases anyway.

In the future, I'd love to develop a faster anti-overcounting strategy than a timeout, but in the meantime, I feel that the timeout really is necessary.

### CODE REVIEW

**Comment by jjkoletar** [comment]
This is great, but I didn't see any unit tests added. Do you have a rationale for not adding any tests?

**Comment by CFSworks** [comment]
I have the best rationale of all: laziness!

In all seriousness -- I should probably unit-test the "object only sends ENTER_INTEREST if the location is acked" behavior. Testing the CA's timeout gets a little bit more... challenging.

**Comment by mgracer48** [comment]
cfsworks has a great sense of humor it seems LOL

**Comment by jjkoletar** [comment]
@CFSworks There, I unit tested the LOCATION_ACK for you

**Comment by CFSworks** [comment]
Thanks, mate! I'm wondering if I should also test the timeout, for the sake of completeness...

**Comment by jjkoletar** [comment]
We probably should have one. 

If you're busy I can probably whip up a test for that today as well.

**Comment by jjkoletar** [comment]
@CFSworks I wrote the test but my machine was being weird about starting any astrond in the context of the unit tests, so I'm not sure it works :)

**Comment by CFSworks** [comment]
@jjkoletar I haven't run the test myself but the code looks great to me. Thanks again! You're a godsend.

**Comment by jjkoletar** [comment]
@CFSworks says the guy who fixed interests :heart_eyes:

**Comment by CFSworks** [comment]
Just ran the tests. This gets :+1: :+1: from me. :shipit:

**Comment by AlJaMa** [comment]
:+1:  on mac :shipit:

**Comment by xHarv14** [comment]
:+1: Code wise. I also haven't ran the tests, but since they pass on OS X and whatever Linux distro @CFSworks ran the tests on, I'll go ahead and merge this down. If this breaks Windows, I'll take the blame, but it's only develop so :heart: :dolphin:

**Pull request merged**
